### ISSUE TITLE
Devdoc building is failing

### ISSUE THREAD

**Issue by homocomputeris** [JuliaDiffEq/DiffEqDevDocs.jl#11]
https://github.com/JuliaDiffEq/DiffEqDevDocs.jl/blob/master/docs/src/contributing/adding_algorithms.md
does not match
https://devdocs.juliadiffeq.org/latest/contributing/adding_algorithms.html

**Comment by ChrisRackauckas** [comment]
Yes, the builds are failing. Let me take a stab at it and see if I can fix it.

**Comment by ChrisRackauckas** [comment]
@kanav99 are you familiar with how to do this? I keep trying and it's failing 🤷‍♂ . Giving you admin.

**Comment by kanav99** [comment]
Let me check this, should not take much time.

**Comment by kanav99** [comment]
I believe the problem is with the hosting deploy key, maybe it expired or something. I will try generating a new key. Would need admin access for that

**Comment by ChrisRackauckas** [comment]
I gave you access

**Comment by kanav99** [comment]
Fixed - https://devdocs.juliadiffeq.org/latest/contributing/adding_algorithms
