### ISSUE TITLE
Is multithreading available in the DP5 method?

### ISSUE THREAD

**Issue by guruvamsi-policharla** [JuliaDiffEq/DiffEqDevDocs.jl#14]
An old notes_on_algorithms doc mentions threading in the context of the DP5 method but I'm unable to find a way to enable it. I checked src/algorithms and it didn't have a field to turn on multithreading. Has it not been implemented yet?
 
Relevant text from https://github.com/JuliaDiffEq/DiffEqDevDocs.jl/blob/a35f6d14e9f7b21ad1e7c1a0f060ea2953f13d96/docs/src/internals/notes_on_algorithms.md:
> The "clear choice" is the Dormand-Prince 4/5 pair. This is the pair which is used by default as ode45 in MATLAB, and serves similar functions in scipy, ODE.jl, etc. The golden standard implementation is Hairer's DOPRI5 (offered by ODEInterface.jl). After optimizations, DifferentialEquations.jl's native DP5 solver is much more efficient (between 4x-400x) than DOPRI5's, with various design choices factoring into this (which are documented in the benchmarks). This is pre-threading, and within method threading will likely be at least doubled or tripled when threading is enabled. Thus it's clear that the reference implementation to try other methods against is the DifferentialEquations.jl DP5 method.

**Comment by ChrisRackauckas** [comment]
Just use an array type that threads broadcast, just like how GPU acceleration is implemented.

**Comment by ChrisRackauckas** [comment]
FWIW, multithreading on BLAS1 requires a pretty big array to be useful, so it's a size-dependent optimization.

**Comment by ChrisRackauckas** [comment]
Closing since I don't see anything actionable here, but feel free to continue the discussion.
